#
#Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "hanish 블로그"
description: > # this means to ignore newlines until "email:"
   Hanish Computer Vision & Deep Learning

email: hanish-@naver.com
#blog logo
logo: "/assets/images/intro.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/back.jpg"

name: 'hanish'
author: 'hanish'
author_image: "/assets/images/intro.jpg"

paginate:	5

url: "https://hanish3464.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@hanish3464'

#fill in disqus shortname to use disqus
disqus: hanish-blog

google_analytics: UA-91026007-2

# social icons and sharing options
social:
  - icon:	#twitter
    url:	#https://twitter.com/dirkfabisch
    desc: #Follow me on twitter
    share_url: #http://twitter.com/share
    share_title: #?text=
    share_link: #"&amp;url="

  - icon:	#facebook
    url:	#https://facebook.com/???
    desc: #Connect with me facebook
    share_url: #https://www.facebook.com/sharer.php
    share_title: #?t=
    share_link: #"&amp;u="

  - icon:	github
    url:	https://github.com/hanish3464
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

markdown: kramdown
